version: 2.1
jobs:
  build_ui:
    docker:
      - image: nixos/nix:2.5.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-cache-{{ arch }}-{{ checksum "ui/yarn.lock" }}
      - run:
          name: "Build"
          command: cd ui && nix-shell --run "yarn install && yarn run bundle"
      - save_cache:
          paths:
            - ui/dce-output
            - ui/node_modules
            - ui/.spago
          key: v1-yarn-cache-{{ arch }}-{{ checksum "ui/yarn.lock" }}
  build_server:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: sudo apt-get update -qq -y && sudo apt-get install -y openssl libssl-dev
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: "Build"
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: "Test"
          command: cargo test
  build_image:
    environment:
      IMAGE_NAME: mujx/blind
      IMAGE_TAG: latest
      DOCKERHUB_USERNAME: mujx
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: Publish image to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build_all:
    jobs:
      - build_ui
      - build_server
      - build_image
