name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-latest
    steps:
    - name: cancel running workflows
      uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d
      with:
        access_token: ${{ github.token }}

  build_ui:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: 18
    - name: Cache pureScript dependencies
      uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
      with:
        key: spago-${{ hashFiles('ui/*.dhall') }}
        path: |
          ui/.spago
          ui/output
          ui/dce-output
    - name: Cache yarn dependencies
      uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
      with:
        key: yarn-${{ hashFiles('ui/yarn.lock') }}
        path: |
          ui/node_modules
          ui/.parcel-cache
    - run: |
        wget https://github.com/MaybeJustJames/zephyr/releases/download/v0.4.0/Linux.tar.gz
        tar xzf Linux.tar.gz && \
        chmod +x zephyr/zephyr && \
        mv zephyr/zephyr /usr/local/bin
    - run: cd ui && yarn install
    - run: cd ui && yarn run bundle

  build_server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
    - uses: actions-rs/toolchain@63eb9591781c46a70274cb3ebdf190fce92702e8
      with:
        toolchain: stable
    - uses: actions-rs/cargo@e7f754b8e09f70ad8eb2c5aebf61e58e8403b210
      with:
        command: build
    - name: Cache cargo dependencies
      uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
      with:
        key: cargo-${{ hashFiles('Cargo.lock') }}
        path: |
          target/
          ~/.cargo
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mujx/blind
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
      - name: Build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
